#!/bin/bash

# Connect to rpi
# First try to connect to rpi over ethernet, then wifi, then zerotier

usage ()
{
    echo "usage:"
    echo "  $0"
    echo "or"
    echo "  $0 HOST"
}

host="rpi"

if [[ $# -eq 1 ]]; then
    host="$1"
elif [[ $# -gt 1 ]]; then
    echo "Illegal number of argument"
    usage
    exit 1
fi

ssh ${host} && exit 0
ssh ${host}-wifi && exit 0
ssh ${host}-zerotier && exit 0
exit 1
