modules:
  - changed-files:
      - any-glob-to-any-file: modules/**/*
nvim:
  - changed-files:
      - any-glob-to-any-file: modules/nvim/**/*
hyprland:
  - changed-files:
      - any-glob-to-any-file: modules/hyprland/**/*
ags:
  - changed-files:
      - any-glob-to-any-file: modules/gui-packages/ags/**/*
secrets:
  - changed-files:
      - any-glob-to-any-file:
        - modules/sops/**/*
        - .sops.yaml
hosts:
  - changed-files:
      - any-glob-to-any-file: hosts/**/*
homes:
  - changed-files:
      - any-glob-to-any-file: homes/**/*
treewide:
  - changed-files:
      - any-glob-to-any-file: "*"
CI:
  - changed-files:
      - any-glob-to-any-file: .github/**/*
