#!/usr/bin/env bash
set -euo pipefail

# If called like `./gc nixpi`

if [ $# -eq 1 ]; then
  if [ "$1" = "nixpi" ]; then
    ssh nixpi 'nix-collect-garbage --delete-old'
    exit 0
  fi
fi

# Garbage collect nix store
nix-collect-garbage --delete-old
