#!/usr/bin/env bash
set -euo pipefail


# Inspect all config:
# ```bash
# nix repl
# :lf .
# nixosConfigurations.nix-yoga.config.michal. <tab>
# ```

# List all custom options. Should be the same for all hosts
# To see more, call ` nix eval ".#nixosConfigurations.nix-yoga.options.michal"` (without --json)
nix eval --json ".#nixosConfigurations.nix-yoga.options.michal" | jq
