#!/usr/bin/env bash
set -euo pipefail

# Function to run the default command
default_command() {
    sudo --preserve-env=IMPURITY_PATH nixos-rebuild switch --flake ".#michal" --impure --log-format internal-json -v |& nom --json
}

# Deploy to nixpi over ssh
update_nixpi() {
    nixos-rebuild switch --flake ".#rpi" --target-host root@nixpi --use-remote-sudo --log-format internal-json -v |& nom --json
}

export IMPURITY_PATH=$(pwd)

# Else, ask for sudo
if [ "${1-default}" = "nixpi" ]; then
    update_nixpi
    exit 0
fi

sudo echo "Running as root"
default_command

