#!/usr/bin/env bash
set -euo pipefail

# `record`
#
# A simple script to start/stop screen recording with `wf-recorder`. Outputs recordings to `~/Videos`.
# TODO: does not support multiple monitors
#
# Options:
# - **`--sound`**: Record a selected area with audio.
# - **`--fullscreen`**: Record the full screen (no audio).
# - **`--fullscreen-sound`**: Record the full screen with audio.
# - *No option*: Record a selected area (no audio).
#
# Stops recording if already running.

getdate() {
    date '+%Y%m%d_%H-%M-%S'
}

cd ~/Videos || exit
if pgrep wf-recorder > /dev/null; then
    notify-send "Recording Stopped" "Stopped" -a 'record-script.sh' &
    pkill wf-recorder &
else
    notify-send "Starting recording" 'recording_'"$(getdate)"'.mp4' -a 'record'
    if [[ "$1" == "--sound" ]]; then
        wf-recorder --pixel-format yuv420p -f './recording_'"$(getdate)"'.mp4' -t --geometry "$(slurp)" --audio=alsa_output.pci-0000_08_00.6.analog-stereo.monitor & disown
    elif [[ "$1" == "--fullscreen-sound" ]]; then
        wf-recorder --pixel-format yuv420p -f './recording_'"$(getdate)"'.mp4' -t --audio=alsa_output.pci-0000_08_00.6.analog-stereo.monitor & disown
    elif [[ "$1" == "--fullscreen" ]]; then
        wf-recorder --pixel-format yuv420p -f './recording_'"$(getdate)"'.mp4' -t & disown
    else 
        wf-recorder --pixel-format yuv420p -f './recording_'"$(getdate)"'.mp4' -t --geometry "$(slurp)" & disown
    fi
fi
