hl.bind("ALT + TAB", hl.dsp.window.cycle_next())
hl.bind("ALT + TAB", hl.dsp.window.bring_to_top())
hl.bind("CTRL + SHIFT + SUPER + up", hl.dsp.window.move({ workspace = "special" }))
hl.bind("SUPER + m", function()
  hl.exec_cmd("hyprctl dispatch movecurrentworkspacetomonitor +1")
end)
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "+1" }))
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "-1" }))
hl.bind("CTRL + SUPER + mouse_up", hl.dsp.focus({ workspace = "+1" }))
hl.bind("CTRL + SUPER + mouse_down", hl.dsp.focus({ workspace = "-1" }))
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind("ALT + I", hl.dsp.exec_cmd("ydotool key 103:1 103:0"), { locked = true, repeating = true })
hl.bind("ALT + K", hl.dsp.exec_cmd("ydotool key 108:1 108:0"), { locked = true, repeating = true })
hl.bind("ALT + J", hl.dsp.exec_cmd("ydotool key 105:1 105:0"), { locked = true, repeating = true })
hl.bind("ALT + L", hl.dsp.exec_cmd("ydotool key 106:1 106:0"), { locked = true, repeating = true })
hl.bind("CTRL + SUPER + R", hl.dsp.exec_cmd("killall ags .ags-wrapped ydotool; ags &"), { release = true })
hl.bind("CTRL + SUPER + ALT + R", hl.dsp.exec_cmd("hyprctl reload; killall ags ydotool; ags &"), { release = true })
