# Source: https://github.com/NotAShelf/nyx/blob/main/.github/workflows/fmt.yml
name: Check flake formatting
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.nix"
      - ".github/workflows/check.yml"
  push:
    paths:
      - "**.nix"
      - ".github/workflows/check.yml"
jobs:
  check-formatting:
    name: "Check flake formatting"
    uses: ./.github/workflows/prelude.yml
    secrets:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    with:
      command: |
        system=$(nix eval --raw --impure --expr builtins.currentSystem)

        nix-fast-build --skip-cached --no-nom \
          --flake .#checks."${system}".fmt-check
