name: Prelude
on:
  workflow_call:
    inputs:
      command:
        required: false
        type: string
      platform:
        default: "ubuntu"
        required: false
        type: string
      optimize-space:
        default: true
        required: false
        type: boolean
    secrets:
      GH_TOKEN:
        required: true
jobs:
  nix:
    runs-on: "${{ inputs.platform }}-latest"
    steps:
      - name: "Maximize build space"
        if: ${{ inputs.optimize-space }}
        uses: easimon/maximize-build-space@v10
        with:
          overprovision-lvm: true
          remove-android: true
          remove-dotnet: true
          remove-haskell: true
          remove-codeql: true

      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.GH_TOKEN }}"

      - name: "Nix Magic Cache"
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: "Install nix-fast-build"
        run: nix profile install nixpkgs#nix-fast-build

      - name: "Run Input: ${{ inputs.command }}"
        run: "${{ inputs.command }}"
